// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxtvdtpfsibjmxmjpxpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94dHZkdHBmc2liam14bWpweHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1OTIzMDcsImV4cCI6MjA1NjE2ODMwN30.FKk6ukZV3NhL0UTv1P0-6ItgLSkeC3qYIjWReQFuHZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);